# sim_commands.py
# autogenerated from sim_commands.h

class Sim_commands():

    def __init__(self):

        self.PAUSE_SIM = 0
        self.RUN_SIM = 1
        self.SIM_SET_WIND_CONDITIONS = 2
        self.COMPUTE_TF = 3
